//
//  Font.swift
//  SwifterCommon
//
//  Created by xxs on 2025/5/8.
//

import Foundation
import SwiftUI

public extension Font {

    static let bold = Bold.self
    static let regular = Regular.self
    static let semibold = Semibold.self
    static let medium = Medium.self
    static let heavy = Heavy.self
    static let light = Light.self
    static let black = Black.self
    static let thin = Thin.self
    static let ultraLight = UltraLight.self

    struct Bold {
        public static let b48: Font = .system(size: 48, weight: .bold)
        public static let b44: Font = .system(size: 44, weight: .bold)
        public static let b40: Font = .system(size: 40, weight: .bold)
        public static let b36: Font = .system(size: 36, weight: .bold)
        public static let b34: Font = .system(size: 34, weight: .bold)
        public static let b32: Font = .system(size: 32, weight: .bold)
        public static let b28: Font = .system(size: 28, weight: .bold)
        public static let b24: Font = .system(size: 24, weight: .bold)
        public static let b23: Font = .system(size: 23, weight: .bold)
        public static let b22: Font = .system(size: 22, weight: .bold)
        public static let b20: Font = .system(size: 20, weight: .bold)
        public static let b18: Font = .system(size: 18, weight: .bold)
        public static let b17: Font = .system(size: 17, weight: .bold)
        public static let b16: Font = .system(size: 16, weight: .bold)
        public static let b15: Font = .system(size: 15, weight: .bold)
        public static let b14: Font = .system(size: 14, weight: .bold)
        public static let b13: Font = .system(size: 13, weight: .bold)
        public static let b12: Font = .system(size: 12, weight: .bold)
        public static let b10: Font = .system(size: 10, weight: .bold)
        public static let b8: Font = .system(size: 8, weight: .bold)
    }

    struct Regular {
        public static let r48: Font = .system(size: 48, weight: .regular)
        public static let r44: Font = .system(size: 44, weight: .regular)
        public static let r40: Font = .system(size: 40, weight: .regular)
        public static let r36: Font = .system(size: 36, weight: .regular)
        public static let r34: Font = .system(size: 34, weight: .regular)
        public static let r32: Font = .system(size: 32, weight: .regular)
        public static let r28: Font = .system(size: 28, weight: .regular)
        public static let r24: Font = .system(size: 24, weight: .regular)
        public static let r23: Font = .system(size: 23, weight: .regular)
        public static let r22: Font = .system(size: 22, weight: .regular)
        public static let r20: Font = .system(size: 20, weight: .regular)
        public static let r18: Font = .system(size: 18, weight: .regular)
        public static let r17: Font = .system(size: 17, weight: .regular)
        public static let r16: Font = .system(size: 16, weight: .regular)
        public static let r15: Font = .system(size: 15, weight: .regular)
        public static let r14: Font = .system(size: 14, weight: .regular)
        public static let r13: Font = .system(size: 13, weight: .regular)
        public static let r12: Font = .system(size: 12, weight: .regular)
        public static let r10: Font = .system(size: 10, weight: .regular)
        public static let r8: Font = .system(size: 8, weight: .regular)
    }

    struct Semibold {
        public static let s48: Font = .system(size: 48, weight: .semibold)
        public static let s44: Font = .system(size: 44, weight: .semibold)
        public static let s40: Font = .system(size: 40, weight: .semibold)
        public static let s36: Font = .system(size: 36, weight: .semibold)
        public static let s34: Font = .system(size: 34, weight: .semibold)
        public static let s32: Font = .system(size: 32, weight: .semibold)
        public static let s28: Font = .system(size: 28, weight: .semibold)
        public static let s24: Font = .system(size: 24, weight: .semibold)
        public static let s23: Font = .system(size: 23, weight: .semibold)
        public static let s22: Font = .system(size: 22, weight: .semibold)
        public static let s20: Font = .system(size: 20, weight: .semibold)
        public static let s18: Font = .system(size: 18, weight: .semibold)
        public static let s17: Font = .system(size: 17, weight: .semibold)
        public static let s16: Font = .system(size: 16, weight: .semibold)
        public static let s15: Font = .system(size: 15, weight: .semibold)
        public static let s14: Font = .system(size: 14, weight: .semibold)
        public static let s13: Font = .system(size: 13, weight: .semibold)
        public static let s12: Font = .system(size: 12, weight: .semibold)
        public static let s10: Font = .system(size: 10, weight: .semibold)
        public static let s8: Font = .system(size: 8, weight: .semibold)
    }

    struct Medium {
        public static let m48: Font = .system(size: 48, weight: .medium)
        public static let m44: Font = .system(size: 44, weight: .medium)
        public static let m40: Font = .system(size: 40, weight: .medium)
        public static let m36: Font = .system(size: 36, weight: .medium)
        public static let m34: Font = .system(size: 34, weight: .medium)
        public static let m32: Font = .system(size: 32, weight: .medium)
        public static let m28: Font = .system(size: 28, weight: .medium)
        public static let m24: Font = .system(size: 24, weight: .medium)
        public static let m23: Font = .system(size: 23, weight: .medium)
        public static let m22: Font = .system(size: 22, weight: .medium)
        public static let m20: Font = .system(size: 20, weight: .medium)
        public static let m18: Font = .system(size: 18, weight: .medium)
        public static let m17: Font = .system(size: 17, weight: .medium)
        public static let m16: Font = .system(size: 16, weight: .medium)
        public static let m15: Font = .system(size: 15, weight: .medium)
        public static let m14: Font = .system(size: 14, weight: .medium)
        public static let m13: Font = .system(size: 13, weight: .medium)
        public static let m12: Font = .system(size: 12, weight: .medium)
        public static let m10: Font = .system(size: 10, weight: .medium)
        public static let m8: Font = .system(size: 8, weight: .medium)
    }

    struct Heavy {
        public static let h48: Font = .system(size: 48, weight: .heavy)
        public static let h44: Font = .system(size: 44, weight: .heavy)
        public static let h40: Font = .system(size: 40, weight: .heavy)
        public static let h36: Font = .system(size: 36, weight: .heavy)
        public static let h34: Font = .system(size: 34, weight: .heavy)
        public static let h32: Font = .system(size: 32, weight: .heavy)
        public static let h28: Font = .system(size: 28, weight: .heavy)
        public static let h24: Font = .system(size: 24, weight: .heavy)
        public static let h23: Font = .system(size: 23, weight: .heavy)
        public static let h22: Font = .system(size: 22, weight: .heavy)
        public static let h20: Font = .system(size: 20, weight: .heavy)
        public static let h18: Font = .system(size: 18, weight: .heavy)
        public static let h17: Font = .system(size: 17, weight: .heavy)
        public static let h16: Font = .system(size: 16, weight: .heavy)
        public static let h15: Font = .system(size: 15, weight: .heavy)
        public static let h14: Font = .system(size: 14, weight: .heavy)
        public static let h13: Font = .system(size: 13, weight: .heavy)
        public static let h12: Font = .system(size: 12, weight: .heavy)
        public static let h10: Font = .system(size: 10, weight: .heavy)
        public static let h8: Font = .system(size: 8, weight: .heavy)
    }

    struct Light {
        public static let l48: Font = .system(size: 48, weight: .light)
        public static let l44: Font = .system(size: 44, weight: .light)
        public static let l40: Font = .system(size: 40, weight: .light)
        public static let l36: Font = .system(size: 36, weight: .light)
        public static let l34: Font = .system(size: 34, weight: .light)
        public static let l32: Font = .system(size: 32, weight: .light)
        public static let l28: Font = .system(size: 28, weight: .light)
        public static let l24: Font = .system(size: 24, weight: .light)
        public static let l23: Font = .system(size: 23, weight: .light)
        public static let l22: Font = .system(size: 22, weight: .light)
        public static let l20: Font = .system(size: 20, weight: .light)
        public static let l18: Font = .system(size: 18, weight: .light)
        public static let l17: Font = .system(size: 17, weight: .light)
        public static let l16: Font = .system(size: 16, weight: .light)
        public static let l15: Font = .system(size: 15, weight: .light)
        public static let l14: Font = .system(size: 14, weight: .light)
        public static let l13: Font = .system(size: 13, weight: .light)
        public static let l12: Font = .system(size: 12, weight: .light)
        public static let l10: Font = .system(size: 10, weight: .light)
        public static let l8: Font = .system(size: 8, weight: .light)
    }

    struct Black {
        public static let b48: Font = .system(size: 48, weight: .black)
        public static let b44: Font = .system(size: 44, weight: .black)
        public static let b40: Font = .system(size: 40, weight: .black)
        public static let b36: Font = .system(size: 36, weight: .black)
        public static let b34: Font = .system(size: 34, weight: .black)
        public static let b32: Font = .system(size: 32, weight: .black)
        public static let b28: Font = .system(size: 28, weight: .black)
        public static let b24: Font = .system(size: 24, weight: .black)
        public static let b23: Font = .system(size: 23, weight: .black)
        public static let b22: Font = .system(size: 22, weight: .black)
        public static let b20: Font = .system(size: 20, weight: .black)
        public static let b18: Font = .system(size: 18, weight: .black)
        public static let b17: Font = .system(size: 17, weight: .black)
        public static let b16: Font = .system(size: 16, weight: .black)
        public static let b15: Font = .system(size: 15, weight: .black)
        public static let b14: Font = .system(size: 14, weight: .black)
        public static let b13: Font = .system(size: 13, weight: .black)
        public static let b12: Font = .system(size: 12, weight: .black)
        public static let b10: Font = .system(size: 10, weight: .black)
        public static let b8: Font = .system(size: 8, weight: .black)
    }

    struct Thin {
        public static let t48: Font = .system(size: 48, weight: .thin)
        public static let t44: Font = .system(size: 44, weight: .thin)
        public static let t40: Font = .system(size: 40, weight: .thin)
        public static let t36: Font = .system(size: 36, weight: .thin)
        public static let t34: Font = .system(size: 34, weight: .thin)
        public static let t32: Font = .system(size: 32, weight: .thin)
        public static let t28: Font = .system(size: 28, weight: .thin)
        public static let t24: Font = .system(size: 24, weight: .thin)
        public static let t23: Font = .system(size: 23, weight: .thin)
        public static let t22: Font = .system(size: 22, weight: .thin)
        public static let t20: Font = .system(size: 20, weight: .thin)
        public static let t18: Font = .system(size: 18, weight: .thin)
        public static let t17: Font = .system(size: 17, weight: .thin)
        public static let t16: Font = .system(size: 16, weight: .thin)
        public static let t15: Font = .system(size: 15, weight: .thin)
        public static let t14: Font = .system(size: 14, weight: .thin)
        public static let t13: Font = .system(size: 13, weight: .thin)
        public static let t12: Font = .system(size: 12, weight: .thin)
        public static let t10: Font = .system(size: 10, weight: .thin)
        public static let t8: Font = .system(size: 8, weight: .thin)
    }

    struct UltraLight {
        public static let ul48: Font = .system(size: 48, weight: .ultraLight)
        public static let ul44: Font = .system(size: 44, weight: .ultraLight)
        public static let ul40: Font = .system(size: 40, weight: .ultraLight)
        public static let ul36: Font = .system(size: 36, weight: .ultraLight)
        public static let ul34: Font = .system(size: 34, weight: .ultraLight)
        public static let ul32: Font = .system(size: 32, weight: .ultraLight)
        public static let ul28: Font = .system(size: 28, weight: .ultraLight)
        public static let ul24: Font = .system(size: 24, weight: .ultraLight)
        public static let ul23: Font = .system(size: 23, weight: .ultraLight)
        public static let ul22: Font = .system(size: 22, weight: .ultraLight)
        public static let ul20: Font = .system(size: 20, weight: .ultraLight)
        public static let ul18: Font = .system(size: 18, weight: .ultraLight)
        public static let ul17: Font = .system(size: 17, weight: .ultraLight)
        public static let ul16: Font = .system(size: 16, weight: .ultraLight)
        public static let ul15: Font = .system(size: 15, weight: .ultraLight)
        public static let ul14: Font = .system(size: 14, weight: .ultraLight)
        public static let ul13: Font = .system(size: 13, weight: .ultraLight)
        public static let ul12: Font = .system(size: 12, weight: .ultraLight)
        public static let ul10: Font = .system(size: 10, weight: .ultraLight)
        public static let ul8: Font = .system(size: 8, weight: .ultraLight)
    }
}

#if os(macOS)
public extension NSFont {
    static let bold = Bold.self
    static let regular = Regular.self
    static let semibold = Semibold.self
    static let medium = Medium.self
    static let heavy = Heavy.self
    static let light = Light.self
    static let black = Black.self
    static let thin = Thin.self
    static let ultraLight = UltraLight.self

    struct Bold {
        @MainActor public static let b48: NSFont = .systemFont(ofSize: 48, weight: .bold)
        @MainActor public static let b44: NSFont = .systemFont(ofSize: 44, weight: .bold)
        @MainActor public static let b40: NSFont = .systemFont(ofSize: 40, weight: .bold)
        @MainActor public static let b36: NSFont = .systemFont(ofSize: 36, weight: .bold)
        @MainActor public static let b34: NSFont = .systemFont(ofSize: 34, weight: .bold)
        @MainActor public static let b32: NSFont = .systemFont(ofSize: 32, weight: .bold)
        @MainActor public static let b28: NSFont = .systemFont(ofSize: 28, weight: .bold)
        @MainActor public static let b24: NSFont = .systemFont(ofSize: 24, weight: .bold)
        @MainActor public static let b23: NSFont = .systemFont(ofSize: 23, weight: .bold)
        @MainActor public static let b22: NSFont = .systemFont(ofSize: 22, weight: .bold)
        @MainActor public static let b20: NSFont = .systemFont(ofSize: 20, weight: .bold)
        @MainActor public static let b18: NSFont = .systemFont(ofSize: 18, weight: .bold)
        @MainActor public static let b17: NSFont = .systemFont(ofSize: 17, weight: .bold)
        @MainActor public static let b16: NSFont = .systemFont(ofSize: 16, weight: .bold)
        @MainActor public static let b15: NSFont = .systemFont(ofSize: 15, weight: .bold)
        @MainActor public static let b14: NSFont = .systemFont(ofSize: 14, weight: .bold)
        @MainActor public static let b13: NSFont = .systemFont(ofSize: 13, weight: .bold)
        @MainActor public static let b12: NSFont = .systemFont(ofSize: 12, weight: .bold)
        @MainActor public static let b10: NSFont = .systemFont(ofSize: 10, weight: .bold)
        @MainActor public static let b8: NSFont = .systemFont(ofSize: 8, weight: .bold)
    }

    struct Regular {
        @MainActor public static let r48: NSFont = .systemFont(ofSize: 48, weight: .regular)
        @MainActor public static let r44: NSFont = .systemFont(ofSize: 44, weight: .regular)
        @MainActor public static let r40: NSFont = .systemFont(ofSize: 40, weight: .regular)
        @MainActor public static let r36: NSFont = .systemFont(ofSize: 36, weight: .regular)
        @MainActor public static let r34: NSFont = .systemFont(ofSize: 34, weight: .regular)
        @MainActor public static let r32: NSFont = .systemFont(ofSize: 32, weight: .regular)
        @MainActor public static let r28: NSFont = .systemFont(ofSize: 28, weight: .regular)
        @MainActor public static let r24: NSFont = .systemFont(ofSize: 24, weight: .regular)
        @MainActor public static let r23: NSFont = .systemFont(ofSize: 23, weight: .regular)
        @MainActor public static let r22: NSFont = .systemFont(ofSize: 22, weight: .regular)
        @MainActor public static let r20: NSFont = .systemFont(ofSize: 20, weight: .regular)
        @MainActor public static let r18: NSFont = .systemFont(ofSize: 18, weight: .regular)
        @MainActor public static let r17: NSFont = .systemFont(ofSize: 17, weight: .regular)
        @MainActor public static let r16: NSFont = .systemFont(ofSize: 16, weight: .regular)
        @MainActor public static let r15: NSFont = .systemFont(ofSize: 15, weight: .regular)
        @MainActor public static let r14: NSFont = .systemFont(ofSize: 14, weight: .regular)
        @MainActor public static let r13: NSFont = .systemFont(ofSize: 13, weight: .regular)
        @MainActor public static let r12: NSFont = .systemFont(ofSize: 12, weight: .regular)
        @MainActor public static let r10: NSFont = .systemFont(ofSize: 10, weight: .regular)
        @MainActor public static let r8: NSFont = .systemFont(ofSize: 8, weight: .regular)
    }

    struct Semibold {
        @MainActor public static let s48: NSFont = .systemFont(ofSize: 48, weight: .semibold)
        @MainActor public static let s44: NSFont = .systemFont(ofSize: 44, weight: .semibold)
        @MainActor public static let s40: NSFont = .systemFont(ofSize: 40, weight: .semibold)
        @MainActor public static let s36: NSFont = .systemFont(ofSize: 36, weight: .semibold)
        @MainActor public static let s34: NSFont = .systemFont(ofSize: 34, weight: .semibold)
        @MainActor public static let s32: NSFont = .systemFont(ofSize: 32, weight: .semibold)
        @MainActor public static let s28: NSFont = .systemFont(ofSize: 28, weight: .semibold)
        @MainActor public static let s24: NSFont = .systemFont(ofSize: 24, weight: .semibold)
        @MainActor public static let s23: NSFont = .systemFont(ofSize: 23, weight: .semibold)
        @MainActor public static let s22: NSFont = .systemFont(ofSize: 22, weight: .semibold)
        @MainActor public static let s20: NSFont = .systemFont(ofSize: 20, weight: .semibold)
        @MainActor public static let s18: NSFont = .systemFont(ofSize: 18, weight: .semibold)
        @MainActor public static let s17: NSFont = .systemFont(ofSize: 17, weight: .semibold)
        @MainActor public static let s16: NSFont = .systemFont(ofSize: 16, weight: .semibold)
        @MainActor public static let s15: NSFont = .systemFont(ofSize: 15, weight: .semibold)
        @MainActor public static let s14: NSFont = .systemFont(ofSize: 14, weight: .semibold)
        @MainActor public static let s13: NSFont = .systemFont(ofSize: 13, weight: .semibold)
        @MainActor public static let s12: NSFont = .systemFont(ofSize: 12, weight: .semibold)
        @MainActor public static let s10: NSFont = .systemFont(ofSize: 10, weight: .semibold)
        @MainActor public static let s8: NSFont = .systemFont(ofSize: 8, weight: .semibold)
    }

    struct Medium {
        @MainActor public static let m48: NSFont = .systemFont(ofSize: 48, weight: .medium)
        @MainActor public static let m44: NSFont = .systemFont(ofSize: 44, weight: .medium)
        @MainActor public static let m40: NSFont = .systemFont(ofSize: 40, weight: .medium)
        @MainActor public static let m36: NSFont = .systemFont(ofSize: 36, weight: .medium)
        @MainActor public static let m34: NSFont = .systemFont(ofSize: 34, weight: .medium)
        @MainActor public static let m32: NSFont = .systemFont(ofSize: 32, weight: .medium)
        @MainActor public static let m28: NSFont = .systemFont(ofSize: 28, weight: .medium)
        @MainActor public static let m24: NSFont = .systemFont(ofSize: 24, weight: .medium)
        @MainActor public static let m23: NSFont = .systemFont(ofSize: 23, weight: .medium)
        @MainActor public static let m22: NSFont = .systemFont(ofSize: 22, weight: .medium)
        @MainActor public static let m20: NSFont = .systemFont(ofSize: 20, weight: .medium)
        @MainActor public static let m18: NSFont = .systemFont(ofSize: 18, weight: .medium)
        @MainActor public static let m17: NSFont = .systemFont(ofSize: 17, weight: .medium)
        @MainActor public static let m16: NSFont = .systemFont(ofSize: 16, weight: .medium)
        @MainActor public static let m15: NSFont = .systemFont(ofSize: 15, weight: .medium)
        @MainActor public static let m14: NSFont = .systemFont(ofSize: 14, weight: .medium)
        @MainActor public static let m13: NSFont = .systemFont(ofSize: 13, weight: .medium)
        @MainActor public static let m12: NSFont = .systemFont(ofSize: 12, weight: .medium)
        @MainActor public static let m10: NSFont = .systemFont(ofSize: 10, weight: .medium)
        @MainActor public static let m8: NSFont = .systemFont(ofSize: 8, weight: .medium)
    }

    struct Heavy {
        @MainActor public static let h48: NSFont = .systemFont(ofSize: 48, weight: .heavy)
        @MainActor public static let h44: NSFont = .systemFont(ofSize: 44, weight: .heavy)
        @MainActor public static let h40: NSFont = .systemFont(ofSize: 40, weight: .heavy)
        @MainActor public static let h36: NSFont = .systemFont(ofSize: 36, weight: .heavy)
        @MainActor public static let h34: NSFont = .systemFont(ofSize: 34, weight: .heavy)
        @MainActor public static let h32: NSFont = .systemFont(ofSize: 32, weight: .heavy)
        @MainActor public static let h28: NSFont = .systemFont(ofSize: 28, weight: .heavy)
        @MainActor public static let h24: NSFont = .systemFont(ofSize: 24, weight: .heavy)
        @MainActor public static let h23: NSFont = .systemFont(ofSize: 23, weight: .heavy)
        @MainActor public static let h22: NSFont = .systemFont(ofSize: 22, weight: .heavy)
        @MainActor public static let h20: NSFont = .systemFont(ofSize: 20, weight: .heavy)
        @MainActor public static let h18: NSFont = .systemFont(ofSize: 18, weight: .heavy)
        @MainActor public static let h17: NSFont = .systemFont(ofSize: 17, weight: .heavy)
        @MainActor public static let h16: NSFont = .systemFont(ofSize: 16, weight: .heavy)
        @MainActor public static let h15: NSFont = .systemFont(ofSize: 15, weight: .heavy)
        @MainActor public static let h14: NSFont = .systemFont(ofSize: 14, weight: .heavy)
        @MainActor public static let h13: NSFont = .systemFont(ofSize: 13, weight: .heavy)
        @MainActor public static let h12: NSFont = .systemFont(ofSize: 12, weight: .heavy)
        @MainActor public static let h10: NSFont = .systemFont(ofSize: 10, weight: .heavy)
        @MainActor public static let h8: NSFont = .systemFont(ofSize: 8, weight: .heavy)
    }

    struct Light {
        @MainActor public static let l48: NSFont = .systemFont(ofSize: 48, weight: .light)
        @MainActor public static let l44: NSFont = .systemFont(ofSize: 44, weight: .light)
        @MainActor public static let l40: NSFont = .systemFont(ofSize: 40, weight: .light)
        @MainActor public static let l36: NSFont = .systemFont(ofSize: 36, weight: .light)
        @MainActor public static let l34: NSFont = .systemFont(ofSize: 34, weight: .light)
        @MainActor public static let l32: NSFont = .systemFont(ofSize: 32, weight: .light)
        @MainActor public static let l28: NSFont = .systemFont(ofSize: 28, weight: .light)
        @MainActor public static let l24: NSFont = .systemFont(ofSize: 24, weight: .light)
        @MainActor public static let l23: NSFont = .systemFont(ofSize: 23, weight: .light)
        @MainActor public static let l22: NSFont = .systemFont(ofSize: 22, weight: .light)
        @MainActor public static let l20: NSFont = .systemFont(ofSize: 20, weight: .light)
        @MainActor public static let l18: NSFont = .systemFont(ofSize: 18, weight: .light)
        @MainActor public static let l17: NSFont = .systemFont(ofSize: 17, weight: .light)
        @MainActor public static let l16: NSFont = .systemFont(ofSize: 16, weight: .light)
        @MainActor public static let l15: NSFont = .systemFont(ofSize: 15, weight: .light)
        @MainActor public static let l14: NSFont = .systemFont(ofSize: 14, weight: .light)
        @MainActor public static let l13: NSFont = .systemFont(ofSize: 13, weight: .light)
        @MainActor public static let l12: NSFont = .systemFont(ofSize: 12, weight: .light)
        @MainActor public static let l10: NSFont = .systemFont(ofSize: 10, weight: .light)
        @MainActor public static let l8: NSFont = .systemFont(ofSize: 8, weight: .light)
    }

    struct Black {
        @MainActor public static let b48: NSFont = .systemFont(ofSize: 48, weight: .black)
        @MainActor public static let b44: NSFont = .systemFont(ofSize: 44, weight: .black)
        @MainActor public static let b40: NSFont = .systemFont(ofSize: 40, weight: .black)
        @MainActor public static let b36: NSFont = .systemFont(ofSize: 36, weight: .black)
        @MainActor public static let b34: NSFont = .systemFont(ofSize: 34, weight: .black)
        @MainActor public static let b32: NSFont = .systemFont(ofSize: 32, weight: .black)
        @MainActor public static let b28: NSFont = .systemFont(ofSize: 28, weight: .black)
        @MainActor public static let b24: NSFont = .systemFont(ofSize: 24, weight: .black)
        @MainActor public static let b23: NSFont = .systemFont(ofSize: 23, weight: .black)
        @MainActor public static let b22: NSFont = .systemFont(ofSize: 22, weight: .black)
        @MainActor public static let b20: NSFont = .systemFont(ofSize: 20, weight: .black)
        @MainActor public static let b18: NSFont = .systemFont(ofSize: 18, weight: .black)
        @MainActor public static let b17: NSFont = .systemFont(ofSize: 17, weight: .black)
        @MainActor public static let b16: NSFont = .systemFont(ofSize: 16, weight: .black)
        @MainActor public static let b15: NSFont = .systemFont(ofSize: 15, weight: .black)
        @MainActor public static let b14: NSFont = .systemFont(ofSize: 14, weight: .black)
        @MainActor public static let b13: NSFont = .systemFont(ofSize: 13, weight: .black)
        @MainActor public static let b12: NSFont = .systemFont(ofSize: 12, weight: .black)
        @MainActor public static let b10: NSFont = .systemFont(ofSize: 10, weight: .black)
        @MainActor public static let b8: NSFont = .systemFont(ofSize: 8, weight: .black)
    }

    struct Thin {
        @MainActor public static let t48: NSFont = .systemFont(ofSize: 48, weight: .thin)
        @MainActor public static let t44: NSFont = .systemFont(ofSize: 44, weight: .thin)
        @MainActor public static let t40: NSFont = .systemFont(ofSize: 40, weight: .thin)
        @MainActor public static let t36: NSFont = .systemFont(ofSize: 36, weight: .thin)
        @MainActor public static let t34: NSFont = .systemFont(ofSize: 34, weight: .thin)
        @MainActor public static let t32: NSFont = .systemFont(ofSize: 32, weight: .thin)
        @MainActor public static let t28: NSFont = .systemFont(ofSize: 28, weight: .thin)
        @MainActor public static let t24: NSFont = .systemFont(ofSize: 24, weight: .thin)
        @MainActor public static let t23: NSFont = .systemFont(ofSize: 23, weight: .thin)
        @MainActor public static let t22: NSFont = .systemFont(ofSize: 22, weight: .thin)
        @MainActor public static let t20: NSFont = .systemFont(ofSize: 20, weight: .thin)
        @MainActor public static let t18: NSFont = .systemFont(ofSize: 18, weight: .thin)
        @MainActor public static let t17: NSFont = .systemFont(ofSize: 17, weight: .thin)
        @MainActor public static let t16: NSFont = .systemFont(ofSize: 16, weight: .thin)
        @MainActor public static let t15: NSFont = .systemFont(ofSize: 15, weight: .thin)
        @MainActor public static let t14: NSFont = .systemFont(ofSize: 14, weight: .thin)
        @MainActor public static let t13: NSFont = .systemFont(ofSize: 13, weight: .thin)
        @MainActor public static let t12: NSFont = .systemFont(ofSize: 12, weight: .thin)
        @MainActor public static let t10: NSFont = .systemFont(ofSize: 10, weight: .thin)
        @MainActor public static let t8: NSFont = .systemFont(ofSize: 8, weight: .thin)
    }

    struct UltraLight {
        @MainActor public static let ul48: NSFont = .systemFont(ofSize: 48, weight: .ultraLight)
        @MainActor public static let ul44: NSFont = .systemFont(ofSize: 44, weight: .ultraLight)
        @MainActor public static let ul40: NSFont = .systemFont(ofSize: 40, weight: .ultraLight)
        @MainActor public static let ul36: NSFont = .systemFont(ofSize: 36, weight: .ultraLight)
        @MainActor public static let ul34: NSFont = .systemFont(ofSize: 34, weight: .ultraLight)
        @MainActor public static let ul32: NSFont = .systemFont(ofSize: 32, weight: .ultraLight)
        @MainActor public static let ul28: NSFont = .systemFont(ofSize: 28, weight: .ultraLight)
        @MainActor public static let ul24: NSFont = .systemFont(ofSize: 24, weight: .ultraLight)
        @MainActor public static let ul23: NSFont = .systemFont(ofSize: 23, weight: .ultraLight)
        @MainActor public static let ul22: NSFont = .systemFont(ofSize: 22, weight: .ultraLight)
        @MainActor public static let ul20: NSFont = .systemFont(ofSize: 20, weight: .ultraLight)
        @MainActor public static let ul18: NSFont = .systemFont(ofSize: 18, weight: .ultraLight)
        @MainActor public static let ul17: NSFont = .systemFont(ofSize: 17, weight: .ultraLight)
        @MainActor public static let ul16: NSFont = .systemFont(ofSize: 16, weight: .ultraLight)
        @MainActor public static let ul15: NSFont = .systemFont(ofSize: 15, weight: .ultraLight)
        @MainActor public static let ul14: NSFont = .systemFont(ofSize: 14, weight: .ultraLight)
        @MainActor public static let ul13: NSFont = .systemFont(ofSize: 13, weight: .ultraLight)
        @MainActor public static let ul12: NSFont = .systemFont(ofSize: 12, weight: .ultraLight)
        @MainActor public static let ul10: NSFont = .systemFont(ofSize: 10, weight: .ultraLight)
        @MainActor public static let ul8: NSFont = .systemFont(ofSize: 8, weight: .ultraLight)
    }
}

#else
public extension UIFont {
    static let bold = Bold.self
    static let regular = Regular.self
    static let semibold = Semibold.self
    static let medium = Medium.self
    static let heavy = Heavy.self
    static let light = Light.self
    static let black = Black.self
    static let thin = Thin.self
    static let ultraLight = UltraLight.self

    struct Bold {
        public static let b48: UIFont = .systemFont(ofSize: 48, weight: .bold)
        public static let b44: UIFont = .systemFont(ofSize: 44, weight: .bold)
        public static let b40: UIFont = .systemFont(ofSize: 40, weight: .bold)
        public static let b36: UIFont = .systemFont(ofSize: 36, weight: .bold)
        public static let b34: UIFont = .systemFont(ofSize: 34, weight: .bold)
        public static let b32: UIFont = .systemFont(ofSize: 32, weight: .bold)
        public static let b28: UIFont = .systemFont(ofSize: 28, weight: .bold)
        public static let b24: UIFont = .systemFont(ofSize: 24, weight: .bold)
        public static let b23: UIFont = .systemFont(ofSize: 23, weight: .bold)
        public static let b22: UIFont = .systemFont(ofSize: 22, weight: .bold)
        public static let b20: UIFont = .systemFont(ofSize: 20, weight: .bold)
        public static let b18: UIFont = .systemFont(ofSize: 18, weight: .bold)
        public static let b17: UIFont = .systemFont(ofSize: 17, weight: .bold)
        public static let b16: UIFont = .systemFont(ofSize: 16, weight: .bold)
        public static let b15: UIFont = .systemFont(ofSize: 15, weight: .bold)
        public static let b14: UIFont = .systemFont(ofSize: 14, weight: .bold)
        public static let b13: UIFont = .systemFont(ofSize: 13, weight: .bold)
        public static let b12: UIFont = .systemFont(ofSize: 12, weight: .bold)
        public static let b10: UIFont = .systemFont(ofSize: 10, weight: .bold)
        public static let b8: UIFont = .systemFont(ofSize: 8, weight: .bold)
    }

    struct Regular {
        public static let r48: UIFont = .systemFont(ofSize: 48, weight: .regular)
        public static let r44: UIFont = .systemFont(ofSize: 44, weight: .regular)
        public static let r40: UIFont = .systemFont(ofSize: 40, weight: .regular)
        public static let r36: UIFont = .systemFont(ofSize: 36, weight: .regular)
        public static let r34: UIFont = .systemFont(ofSize: 34, weight: .regular)
        public static let r32: UIFont = .systemFont(ofSize: 32, weight: .regular)
        public static let r28: UIFont = .systemFont(ofSize: 28, weight: .regular)
        public static let r24: UIFont = .systemFont(ofSize: 24, weight: .regular)
        public static let r23: UIFont = .systemFont(ofSize: 23, weight: .regular)
        public static let r22: UIFont = .systemFont(ofSize: 22, weight: .regular)
        public static let r20: UIFont = .systemFont(ofSize: 20, weight: .regular)
        public static let r18: UIFont = .systemFont(ofSize: 18, weight: .regular)
        public static let r17: UIFont = .systemFont(ofSize: 17, weight: .regular)
        public static let r16: UIFont = .systemFont(ofSize: 16, weight: .regular)
        public static let r15: UIFont = .systemFont(ofSize: 15, weight: .regular)
        public static let r14: UIFont = .systemFont(ofSize: 14, weight: .regular)
        public static let r13: UIFont = .systemFont(ofSize: 13, weight: .regular)
        public static let r12: UIFont = .systemFont(ofSize: 12, weight: .regular)
        public static let r10: UIFont = .systemFont(ofSize: 10, weight: .regular)
        public static let r8: UIFont = .systemFont(ofSize: 8, weight: .regular)
    }

    struct Semibold {
        public static let s48: UIFont = .systemFont(ofSize: 48, weight: .semibold)
        public static let s44: UIFont = .systemFont(ofSize: 44, weight: .semibold)
        public static let s40: UIFont = .systemFont(ofSize: 40, weight: .semibold)
        public static let s36: UIFont = .systemFont(ofSize: 36, weight: .semibold)
        public static let s34: UIFont = .systemFont(ofSize: 34, weight: .semibold)
        public static let s32: UIFont = .systemFont(ofSize: 32, weight: .semibold)
        public static let s28: UIFont = .systemFont(ofSize: 28, weight: .semibold)
        public static let s24: UIFont = .systemFont(ofSize: 24, weight: .semibold)
        public static let s23: UIFont = .systemFont(ofSize: 23, weight: .semibold)
        public static let s22: UIFont = .systemFont(ofSize: 22, weight: .semibold)
        public static let s20: UIFont = .systemFont(ofSize: 20, weight: .semibold)
        public static let s18: UIFont = .systemFont(ofSize: 18, weight: .semibold)
        public static let s17: UIFont = .systemFont(ofSize: 17, weight: .semibold)
        public static let s16: UIFont = .systemFont(ofSize: 16, weight: .semibold)
        public static let s15: UIFont = .systemFont(ofSize: 15, weight: .semibold)
        public static let s14: UIFont = .systemFont(ofSize: 14, weight: .semibold)
        public static let s13: UIFont = .systemFont(ofSize: 13, weight: .semibold)
        public static let s12: UIFont = .systemFont(ofSize: 12, weight: .semibold)
        public static let s10: UIFont = .systemFont(ofSize: 10, weight: .semibold)
        public static let s8: UIFont = .systemFont(ofSize: 8, weight: .semibold)
    }

    struct Medium {
        public static let m48: UIFont = .systemFont(ofSize: 48, weight: .medium)
        public static let m44: UIFont = .systemFont(ofSize: 44, weight: .medium)
        public static let m40: UIFont = .systemFont(ofSize: 40, weight: .medium)
        public static let m36: UIFont = .systemFont(ofSize: 36, weight: .medium)
        public static let m34: UIFont = .systemFont(ofSize: 34, weight: .medium)
        public static let m32: UIFont = .systemFont(ofSize: 32, weight: .medium)
        public static let m28: UIFont = .systemFont(ofSize: 28, weight: .medium)
        public static let m24: UIFont = .systemFont(ofSize: 24, weight: .medium)
        public static let m23: UIFont = .systemFont(ofSize: 23, weight: .medium)
        public static let m22: UIFont = .systemFont(ofSize: 22, weight: .medium)
        public static let m20: UIFont = .systemFont(ofSize: 20, weight: .medium)
        public static let m18: UIFont = .systemFont(ofSize: 18, weight: .medium)
        public static let m17: UIFont = .systemFont(ofSize: 17, weight: .medium)
        public static let m16: UIFont = .systemFont(ofSize: 16, weight: .medium)
        public static let m15: UIFont = .systemFont(ofSize: 15, weight: .medium)
        public static let m14: UIFont = .systemFont(ofSize: 14, weight: .medium)
        public static let m13: UIFont = .systemFont(ofSize: 13, weight: .medium)
        public static let m12: UIFont = .systemFont(ofSize: 12, weight: .medium)
        public static let m10: UIFont = .systemFont(ofSize: 10, weight: .medium)
        public static let m8: UIFont = .systemFont(ofSize: 8, weight: .medium)
    }

    struct Heavy {
        public static let h48: UIFont = .systemFont(ofSize: 48, weight: .heavy)
        public static let h44: UIFont = .systemFont(ofSize: 44, weight: .heavy)
        public static let h40: UIFont = .systemFont(ofSize: 40, weight: .heavy)
        public static let h36: UIFont = .systemFont(ofSize: 36, weight: .heavy)
        public static let h34: UIFont = .systemFont(ofSize: 34, weight: .heavy)
        public static let h32: UIFont = .systemFont(ofSize: 32, weight: .heavy)
        public static let h28: UIFont = .systemFont(ofSize: 28, weight: .heavy)
        public static let h24: UIFont = .systemFont(ofSize: 24, weight: .heavy)
        public static let h23: UIFont = .systemFont(ofSize: 23, weight: .heavy)
        public static let h22: UIFont = .systemFont(ofSize: 22, weight: .heavy)
        public static let h20: UIFont = .systemFont(ofSize: 20, weight: .heavy)
        public static let h18: UIFont = .systemFont(ofSize: 18, weight: .heavy)
        public static let h17: UIFont = .systemFont(ofSize: 17, weight: .heavy)
        public static let h16: UIFont = .systemFont(ofSize: 16, weight: .heavy)
        public static let h15: UIFont = .systemFont(ofSize: 15, weight: .heavy)
        public static let h14: UIFont = .systemFont(ofSize: 14, weight: .heavy)
        public static let h13: UIFont = .systemFont(ofSize: 13, weight: .heavy)
        public static let h12: UIFont = .systemFont(ofSize: 12, weight: .heavy)
        public static let h10: UIFont = .systemFont(ofSize: 10, weight: .heavy)
        public static let h8: UIFont = .systemFont(ofSize: 8, weight: .heavy)
    }

    struct Light {
        public static let l48: UIFont = .systemFont(ofSize: 48, weight: .light)
        public static let l44: UIFont = .systemFont(ofSize: 44, weight: .light)
        public static let l40: UIFont = .systemFont(ofSize: 40, weight: .light)
        public static let l36: UIFont = .systemFont(ofSize: 36, weight: .light)
        public static let l34: UIFont = .systemFont(ofSize: 34, weight: .light)
        public static let l32: UIFont = .systemFont(ofSize: 32, weight: .light)
        public static let l28: UIFont = .systemFont(ofSize: 28, weight: .light)
        public static let l24: UIFont = .systemFont(ofSize: 24, weight: .light)
        public static let l23: UIFont = .systemFont(ofSize: 23, weight: .light)
        public static let l22: UIFont = .systemFont(ofSize: 22, weight: .light)
        public static let l20: UIFont = .systemFont(ofSize: 20, weight: .light)
        public static let l18: UIFont = .systemFont(ofSize: 18, weight: .light)
        public static let l17: UIFont = .systemFont(ofSize: 17, weight: .light)
        public static let l16: UIFont = .systemFont(ofSize: 16, weight: .light)
        public static let l15: UIFont = .systemFont(ofSize: 15, weight: .light)
        public static let l14: UIFont = .systemFont(ofSize: 14, weight: .light)
        public static let l13: UIFont = .systemFont(ofSize: 13, weight: .light)
        public static let l12: UIFont = .systemFont(ofSize: 12, weight: .light)
        public static let l10: UIFont = .systemFont(ofSize: 10, weight: .light)
        public static let l8: UIFont = .systemFont(ofSize: 8, weight: .light)
    }

    struct Black {
        public static let b48: UIFont = .systemFont(ofSize: 48, weight: .black)
        public static let b44: UIFont = .systemFont(ofSize: 44, weight: .black)
        public static let b40: UIFont = .systemFont(ofSize: 40, weight: .black)
        public static let b36: UIFont = .systemFont(ofSize: 36, weight: .black)
        public static let b34: UIFont = .systemFont(ofSize: 34, weight: .black)
        public static let b32: UIFont = .systemFont(ofSize: 32, weight: .black)
        public static let b28: UIFont = .systemFont(ofSize: 28, weight: .black)
        public static let b24: UIFont = .systemFont(ofSize: 24, weight: .black)
        public static let b23: UIFont = .systemFont(ofSize: 23, weight: .black)
        public static let b22: UIFont = .systemFont(ofSize: 22, weight: .black)
        public static let b20: UIFont = .systemFont(ofSize: 20, weight: .black)
        public static let b18: UIFont = .systemFont(ofSize: 18, weight: .black)
        public static let b17: UIFont = .systemFont(ofSize: 17, weight: .black)
        public static let b16: UIFont = .systemFont(ofSize: 16, weight: .black)
        public static let b15: UIFont = .systemFont(ofSize: 15, weight: .black)
        public static let b14: UIFont = .systemFont(ofSize: 14, weight: .black)
        public static let b13: UIFont = .systemFont(ofSize: 13, weight: .black)
        public static let b12: UIFont = .systemFont(ofSize: 12, weight: .black)
        public static let b10: UIFont = .systemFont(ofSize: 10, weight: .black)
        public static let b8: UIFont = .systemFont(ofSize: 8, weight: .black)
    }

    struct Thin {
        public static let t48: UIFont = .systemFont(ofSize: 48, weight: .thin)
        public static let t44: UIFont = .systemFont(ofSize: 44, weight: .thin)
        public static let t40: UIFont = .systemFont(ofSize: 40, weight: .thin)
        public static let t36: UIFont = .systemFont(ofSize: 36, weight: .thin)
        public static let t34: UIFont = .systemFont(ofSize: 34, weight: .thin)
        public static let t32: UIFont = .systemFont(ofSize: 32, weight: .thin)
        public static let t28: UIFont = .systemFont(ofSize: 28, weight: .thin)
        public static let t24: UIFont = .systemFont(ofSize: 24, weight: .thin)
        public static let t23: UIFont = .systemFont(ofSize: 23, weight: .thin)
        public static let t22: UIFont = .systemFont(ofSize: 22, weight: .thin)
        public static let t20: UIFont = .systemFont(ofSize: 20, weight: .thin)
        public static let t18: UIFont = .systemFont(ofSize: 18, weight: .thin)
        public static let t17: UIFont = .systemFont(ofSize: 17, weight: .thin)
        public static let t16: UIFont = .systemFont(ofSize: 16, weight: .thin)
        public static let t15: UIFont = .systemFont(ofSize: 15, weight: .thin)
        public static let t14: UIFont = .systemFont(ofSize: 14, weight: .thin)
        public static let t13: UIFont = .systemFont(ofSize: 13, weight: .thin)
        public static let t12: UIFont = .systemFont(ofSize: 12, weight: .thin)
        public static let t10: UIFont = .systemFont(ofSize: 10, weight: .thin)
        public static let t8: UIFont = .systemFont(ofSize: 8, weight: .thin)
    }

    struct UltraLight {
        public static let ul48: UIFont = .systemFont(ofSize: 48, weight: .ultraLight)
        public static let ul44: UIFont = .systemFont(ofSize: 44, weight: .ultraLight)
        public static let ul40: UIFont = .systemFont(ofSize: 40, weight: .ultraLight)
        public static let ul36: UIFont = .systemFont(ofSize: 36, weight: .ultraLight)
        public static let ul34: UIFont = .systemFont(ofSize: 34, weight: .ultraLight)
        public static let ul32: UIFont = .systemFont(ofSize: 32, weight: .ultraLight)
        public static let ul28: UIFont = .systemFont(ofSize: 28, weight: .ultraLight)
        public static let ul24: UIFont = .systemFont(ofSize: 24, weight: .ultraLight)
        public static let ul23: UIFont = .systemFont(ofSize: 23, weight: .ultraLight)
        public static let ul22: UIFont = .systemFont(ofSize: 22, weight: .ultraLight)
        public static let ul20: UIFont = .systemFont(ofSize: 20, weight: .ultraLight)
        public static let ul18: UIFont = .systemFont(ofSize: 18, weight: .ultraLight)
        public static let ul17: UIFont = .systemFont(ofSize: 17, weight: .ultraLight)
        public static let ul16: UIFont = .systemFont(ofSize: 16, weight: .ultraLight)
        public static let ul15: UIFont = .systemFont(ofSize: 15, weight: .ultraLight)
        public static let ul14: UIFont = .systemFont(ofSize: 14, weight: .ultraLight)
        public static let ul13: UIFont = .systemFont(ofSize: 13, weight: .ultraLight)
        public static let ul12: UIFont = .systemFont(ofSize: 12, weight: .ultraLight)
        public static let ul10: UIFont = .systemFont(ofSize: 10, weight: .ultraLight)
        public static let ul8: UIFont = .systemFont(ofSize: 8, weight: .ultraLight)
    }
}
#endif
